package View;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


public class frmLogin extends javax.swing.JFrame {

    public frmLogin() {
        initComponents();                        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondPanel();
        lbTitle = new javax.swing.JLabel();
        lbCheck1 = new javax.swing.JLabel();
        txtAccount = new javax.swing.JTextField();
        lbAccount = new javax.swing.JLabel();
        lbAccountError = new javax.swing.JLabel();
        lbChek2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        lbPassword = new javax.swing.JLabel();
        lbPassError = new javax.swing.JLabel();
        chbViewPass = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entrar al Sistema");
        setIconImage(getIconLogin());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        jPanel1.add(lbTitle);
        lbTitle.setBounds(10, 10, 570, 100);

        lbCheck1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/accept1.png"))); // NOI18N
        jPanel1.add(lbCheck1);
        lbCheck1.setBounds(340, 140, 30, 30);

        txtAccount.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jPanel1.add(txtAccount);
        txtAccount.setBounds(150, 140, 190, 30);

        lbAccount.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbAccount.setForeground(new java.awt.Color(50, 255, 50));
        lbAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/usuario.png"))); // NOI18N
        lbAccount.setText("Usuario:");
        jPanel1.add(lbAccount);
        lbAccount.setBounds(20, 140, 110, 30);

        lbAccountError.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbAccountError.setForeground(new java.awt.Color(255, 0, 0));
        lbAccountError.setText("* Campo Requerido");
        jPanel1.add(lbAccountError);
        lbAccountError.setBounds(30, 170, 290, 19);

        lbChek2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/accept1.png"))); // NOI18N
        lbChek2.setText(" ");
        jPanel1.add(lbChek2);
        lbChek2.setBounds(340, 200, 30, 30);

        txtPass.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jPanel1.add(txtPass);
        txtPass.setBounds(150, 200, 190, 30);

        lbPassword.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(51, 255, 51));
        lbPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/PASSWORD.png"))); // NOI18N
        lbPassword.setText("Contraseña:");
        jPanel1.add(lbPassword);
        lbPassword.setBounds(10, 200, 131, 30);

        lbPassError.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbPassError.setForeground(new java.awt.Color(255, 0, 0));
        lbPassError.setText("* Campo Requerido");
        jPanel1.add(lbPassError);
        lbPassError.setBounds(30, 230, 290, 19);

        chbViewPass.setFont(new java.awt.Font("Engravers MT", 1, 10)); // NOI18N
        chbViewPass.setForeground(new java.awt.Color(51, 51, 51));
        chbViewPass.setText("Mostrar Contraseña");
        chbViewPass.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(chbViewPass);
        chbViewPass.setBounds(120, 250, 195, 20);

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "IDENTIFICARCE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 120, 370, 160);

        btnEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ACCEPT.png"))); // NOI18N
        btnEnter.setText("INGRESAR");
        jPanel1.add(btnEnter);
        btnEnter.setBounds(50, 320, 130, 30);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/CANCEL.png"))); // NOI18N
        btnExit.setText("SALIR");
        jPanel1.add(btnExit);
        btnExit.setBounds(300, 320, 120, 30);

        lbLogo.setName(""); // NOI18N
        jPanel1.add(lbLogo);
        lbLogo.setBounds(340, 110, 240, 220);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-5, -5, 580, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Image getIconLogin(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Image/login.png"));
        return retValue;
    }    

    class FondPanel extends JPanel {

        private Image image;

        @Override
        public void paint(Graphics g) {
            image = new ImageIcon(getClass().getResource("/Image/Fondo 3.jpg")).getImage();
            g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEnter;
    public javax.swing.JButton btnExit;
    public javax.swing.JCheckBox chbViewPass;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbAccount;
    public javax.swing.JLabel lbAccountError;
    public javax.swing.JLabel lbCheck1;
    public javax.swing.JLabel lbChek2;
    public javax.swing.JLabel lbLogo;
    public javax.swing.JLabel lbPassError;
    public javax.swing.JLabel lbPassword;
    public javax.swing.JLabel lbTitle;
    public javax.swing.JTextField txtAccount;
    public javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables

}
