package View;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

public class frmManager extends javax.swing.JFrame {    
    
    public frmManager() {
        initComponents();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Icon/Pharmacy icon1.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new FondPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jdcExpiration = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSpecification = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        lbNameError = new javax.swing.JLabel();
        lbPriceError = new javax.swing.JLabel();
        lbQuantityError = new javax.swing.JLabel();
        lbDescriptionError = new javax.swing.JLabel();
        lbSpecificationError = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new FondPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        txtSearchName = new javax.swing.JTextField();
        txtSearchDescription = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTbuscar = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtEditName = new javax.swing.JTextField();
        jdcEditExpiration = new com.toedter.calendar.JDateChooser();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtEditDescription = new javax.swing.JTextArea();
        txtEditPrice = new javax.swing.JTextField();
        txtEditQuantity = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtEditSpecification = new javax.swing.JTextArea();
        btnAccept = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GERENTE");
        setIconImage(getIconImage());
        getContentPane().setLayout(null);

        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setOpaque(true);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 255, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "AGREGAR PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Nombre del Producto:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 50, 185, 20);

        txtName.setMaximumSize(new java.awt.Dimension(14, 40));
        jPanel2.add(txtName);
        txtName.setBounds(190, 50, 185, 20);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Caducidad:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 90, 100, 50);
        jPanel2.add(jdcExpiration);
        jdcExpiration.setBounds(110, 100, 170, 30);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("Precio:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(390, 50, 60, 20);
        jPanel2.add(txtPrice);
        txtPrice.setBounds(460, 50, 200, 20);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 255));
        jLabel8.setText("Existencia:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(390, 100, 90, 20);

        txtQuantity.setToolTipText("");
        txtQuantity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(txtQuantity);
        txtQuantity.setBounds(480, 100, 160, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 255));
        jLabel9.setText("Unid.");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(650, 100, 40, 20);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Descripcion:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(130, 180, 95, 18);

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(txtDescription);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 350, 150);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 255));
        jLabel10.setText("Especificaciones: ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(480, 180, 150, 20);

        txtSpecification.setColumns(20);
        txtSpecification.setRows(5);
        jScrollPane2.setViewportView(txtSpecification);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(400, 210, 290, 150);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add.png"))); // NOI18N
        btnAdd.setText("AGREGAR");
        jPanel2.add(btnAdd);
        btnAdd.setBounds(310, 390, 150, 40);

        lbNameError.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbNameError.setForeground(new java.awt.Color(255, 0, 0));
        lbNameError.setText("* Campo Requerido");
        jPanel2.add(lbNameError);
        lbNameError.setBounds(70, 70, 290, 19);

        lbPriceError.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbPriceError.setForeground(new java.awt.Color(255, 0, 0));
        lbPriceError.setText("* Campo Requerido");
        jPanel2.add(lbPriceError);
        lbPriceError.setBounds(390, 70, 290, 19);

        lbQuantityError.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbQuantityError.setForeground(new java.awt.Color(255, 0, 0));
        lbQuantityError.setText("* Campo Requerido");
        jPanel2.add(lbQuantityError);
        lbQuantityError.setBounds(390, 130, 290, 19);

        lbDescriptionError.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbDescriptionError.setForeground(new java.awt.Color(255, 0, 0));
        lbDescriptionError.setText("* Campo Requerido");
        jPanel2.add(lbDescriptionError);
        lbDescriptionError.setBounds(30, 360, 290, 19);

        lbSpecificationError.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbSpecificationError.setForeground(new java.awt.Color(255, 0, 0));
        lbSpecificationError.setText("* Campo Requerido");
        jPanel2.add(lbSpecificationError);
        lbSpecificationError.setBounds(390, 360, 290, 19);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 740, 450);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 290, 80);

        jTabbedPane1.addTab("Agregar", new javax.swing.ImageIcon(getClass().getResource("/Icon/ADD PURCHASE.png")), jPanel1, "Agregar un Producto"); // NOI18N

        jPanel4.setOpaque(false);
        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(null);

        jLabel20.setForeground(new java.awt.Color(0, 255, 255));
        jLabel20.setText("ID USUARIO:");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(650, 20, 72, 20);

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 255, 255));
        jLabel21.setText("Busqueda por Nombre:");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(30, 40, 181, 18);

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 255, 255));
        jLabel22.setText("O Descripcion:");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(370, 40, 120, 30);

        jTID.setEditable(false);
        jTID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jTID);
        jTID.setBounds(730, 20, 70, 24);
        jPanel5.add(txtSearchName);
        txtSearchName.setBounds(210, 40, 150, 24);
        jPanel5.add(txtSearchDescription);
        txtSearchDescription.setBounds(490, 40, 150, 24);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit.png"))); // NOI18N
        btnEdit.setText("MODIFICAR");
        jPanel5.add(btnEdit);
        btnEdit.setBounds(320, 280, 170, 40);

        jTbuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTbuscar.setColumnSelectionAllowed(true);
        jTbuscar.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTbuscar);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(40, 70, 750, 200);

        jLabel23.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.add(jLabel23);
        jLabel23.setBounds(10, 10, 800, 320);

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 255, 255));
        jLabel24.setText("Nombre Producto:");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(40, 350, 143, 18);

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 255, 255));
        jLabel25.setText("Caducidad:");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(40, 380, 87, 18);

        jLabel26.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 255, 255));
        jLabel26.setText("Descripción:");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(150, 410, 95, 18);

        jLabel27.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 255, 255));
        jLabel27.setText("Precio:");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(460, 350, 54, 18);

        jLabel28.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 255, 255));
        jLabel28.setText("Existencia:");
        jPanel5.add(jLabel28);
        jLabel28.setBounds(460, 380, 83, 18);

        jLabel29.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 255, 255));
        jLabel29.setText("Especificaciones:");
        jPanel5.add(jLabel29);
        jLabel29.setBounds(540, 410, 131, 18);

        txtEditName.setEditable(false);
        jPanel5.add(txtEditName);
        txtEditName.setBounds(190, 350, 220, 24);
        jPanel5.add(jdcEditExpiration);
        jdcEditExpiration.setBounds(190, 380, 170, 30);

        txtEditDescription.setEditable(false);
        txtEditDescription.setColumns(20);
        txtEditDescription.setRows(5);
        jScrollPane8.setViewportView(txtEditDescription);

        jPanel5.add(jScrollPane8);
        jScrollPane8.setBounds(40, 430, 320, 130);

        txtEditPrice.setEditable(false);
        jPanel5.add(txtEditPrice);
        txtEditPrice.setBounds(550, 350, 110, 24);

        txtEditQuantity.setEditable(false);
        jPanel5.add(txtEditQuantity);
        txtEditQuantity.setBounds(550, 380, 110, 24);

        txtEditSpecification.setEditable(false);
        txtEditSpecification.setColumns(20);
        txtEditSpecification.setRows(5);
        jScrollPane7.setViewportView(txtEditSpecification);

        jPanel5.add(jScrollPane7);
        jScrollPane7.setBounds(460, 430, 310, 130);

        btnAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ACCEPT.png"))); // NOI18N
        btnAccept.setText("ACEPTAR");
        jPanel5.add(btnAccept);
        btnAccept.setBounds(340, 570, 170, 40);

        jLabel30.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Modificar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.add(jLabel30);
        jLabel30.setBounds(10, 330, 800, 300);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(0, 0, 830, 640);
        jPanel4.add(jLabel11);
        jLabel11.setBounds(0, 0, 290, 80);

        jTabbedPane1.addTab("Buscar/Modificar", new javax.swing.ImageIcon(getClass().getResource("/Icon/Search.png")), jPanel4, "Buscar Producto y Modificarlo"); // NOI18N

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 860, 700);
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        jMenu1.setText("Modificar");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Contraseña");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Info");

        jMenuItem2.setText("Acerca de...");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Salir");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Cerrar Sesion");
        jMenu4.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("Salir");
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    class FondPanel extends JPanel {
        private Image image;
        @Override
        public void paint(Graphics g) {
            image = new ImageIcon(getClass().getResource("/Image/Fondo 2.jpg")).getImage();
            g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAccept;
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnEdit;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel29;
    public javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu4;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JMenuItem jMenuItem4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JTextField jTID;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTbuscar;
    public com.toedter.calendar.JDateChooser jdcEditExpiration;
    public com.toedter.calendar.JDateChooser jdcExpiration;
    public javax.swing.JLabel lbDescriptionError;
    public javax.swing.JLabel lbNameError;
    public javax.swing.JLabel lbPriceError;
    public javax.swing.JLabel lbQuantityError;
    public javax.swing.JLabel lbSpecificationError;
    public javax.swing.JTextArea txtDescription;
    public javax.swing.JTextArea txtEditDescription;
    public javax.swing.JTextField txtEditName;
    public javax.swing.JTextField txtEditPrice;
    public javax.swing.JTextField txtEditQuantity;
    public javax.swing.JTextArea txtEditSpecification;
    public javax.swing.JTextField txtName;
    public javax.swing.JTextField txtPrice;
    public javax.swing.JTextField txtQuantity;
    public javax.swing.JTextField txtSearchDescription;
    public javax.swing.JTextField txtSearchName;
    public javax.swing.JTextArea txtSpecification;
    // End of variables declaration//GEN-END:variables
}
