package View;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class frmRegister extends javax.swing.JFrame {

    frmRegister.FondPanel fond = new frmRegister.FondPanel();
    public frmRegister() {
        this.setContentPane(fond);
        initComponents();
        
    }
    
    public Image getIconLogin(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Icon/AddUser.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel35 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbCheck1 = new javax.swing.JLabel();
        lbNameError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPathern = new javax.swing.JTextField();
        lbCheck2 = new javax.swing.JLabel();
        lbPathernError = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMother = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbCheck3 = new javax.swing.JLabel();
        lbMotherError = new javax.swing.JLabel();
        txtAccount = new javax.swing.JTextField();
        lbCheck4 = new javax.swing.JLabel();
        lbAccountError = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        lbCheck5 = new javax.swing.JLabel();
        lbPassError = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRepitPass = new javax.swing.JPasswordField();
        lbCheck6 = new javax.swing.JLabel();
        lbRepitError = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCnivel = new javax.swing.JComboBox();
        btnAdd = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel35.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Agregar Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        setTitle("Agregar Usuario");
        setIconImage(getIconLogin());
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "NUEVO USUARIO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Nombre: ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 60, 72, 18);

        txtName.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        jPanel1.add(txtName);
        txtName.setBounds(210, 50, 260, 29);

        lbCheck1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/accept1.png"))); // NOI18N
        jPanel1.add(lbCheck1);
        lbCheck1.setBounds(480, 50, 30, 30);

        lbNameError.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbNameError.setForeground(new java.awt.Color(255, 0, 0));
        lbNameError.setText("* Campo Requerido");
        jPanel1.add(lbNameError);
        lbNameError.setBounds(220, 80, 290, 19);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Apellido Paterno:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 110, 134, 18);

        txtPathern.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtPathern.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPathernKeyTyped(evt);
            }
        });
        jPanel1.add(txtPathern);
        txtPathern.setBounds(210, 100, 260, 28);

        lbCheck2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/accept1.png"))); // NOI18N
        jPanel1.add(lbCheck2);
        lbCheck2.setBounds(480, 100, 30, 30);

        lbPathernError.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbPathernError.setForeground(new java.awt.Color(255, 0, 0));
        lbPathernError.setText("* Campo Requerido");
        jPanel1.add(lbPathernError);
        lbPathernError.setBounds(220, 130, 290, 19);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Apellido Materno:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 160, 137, 18);

        txtMother.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtMother.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMotherKeyTyped(evt);
            }
        });
        jPanel1.add(txtMother);
        txtMother.setBounds(210, 150, 260, 30);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("Cuenta Usuario:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 200, 125, 18);

        lbCheck3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/accept1.png"))); // NOI18N
        jPanel1.add(lbCheck3);
        lbCheck3.setBounds(480, 150, 30, 30);

        lbMotherError.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbMotherError.setForeground(new java.awt.Color(255, 0, 0));
        lbMotherError.setText("* Campo Requerido");
        jPanel1.add(lbMotherError);
        lbMotherError.setBounds(220, 180, 290, 19);

        txtAccount.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtAccount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAccountKeyTyped(evt);
            }
        });
        jPanel1.add(txtAccount);
        txtAccount.setBounds(210, 200, 260, 28);

        lbCheck4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/accept1.png"))); // NOI18N
        jPanel1.add(lbCheck4);
        lbCheck4.setBounds(480, 200, 30, 30);

        lbAccountError.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbAccountError.setForeground(new java.awt.Color(255, 0, 0));
        lbAccountError.setText("* Campo Requerido");
        jPanel1.add(lbAccountError);
        lbAccountError.setBounds(220, 230, 290, 19);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 250, 95, 18);

        txtPass.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });
        jPanel1.add(txtPass);
        txtPass.setBounds(210, 250, 260, 30);

        lbCheck5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/accept1.png"))); // NOI18N
        jPanel1.add(lbCheck5);
        lbCheck5.setBounds(480, 250, 30, 30);

        lbPassError.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbPassError.setForeground(new java.awt.Color(255, 0, 0));
        lbPassError.setText("* Campo Requerido");
        jPanel1.add(lbPassError);
        lbPassError.setBounds(220, 280, 290, 19);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Repetir Contraseña:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 300, 156, 18);

        txtRepitPass.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtRepitPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRepitPassKeyTyped(evt);
            }
        });
        jPanel1.add(txtRepitPass);
        txtRepitPass.setBounds(210, 300, 260, 30);

        lbCheck6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/accept1.png"))); // NOI18N
        jPanel1.add(lbCheck6);
        lbCheck6.setBounds(480, 300, 30, 30);

        lbRepitError.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbRepitError.setForeground(new java.awt.Color(255, 0, 0));
        lbRepitError.setText("* Campo Requerido");
        jPanel1.add(lbRepitError);
        lbRepitError.setBounds(220, 330, 290, 19);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("Tipo de Usuario:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 360, 150, 18);

        jCnivel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCnivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Empleado", "Encargado" }));
        jPanel1.add(jCnivel);
        jCnivel.setBounds(280, 360, 120, 25);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/AddUser1.png"))); // NOI18N
        btnAdd.setText("Agregar");
        jPanel1.add(btnAdd);
        btnAdd.setBounds(180, 400, 170, 36);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 450);

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Cancelar");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Info");

        jMenuItem2.setText("Acerca de...");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        // TODO add your handling code here:
        int k = (int) evt.getKeyChar();
        if (k > 47 && k < 58) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(rootPane, "Solo puede ingresar letras.....!!!");
        }
        int numerocaracteres = 15;
        if (txtName.getText().length() >= numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo puede ingresar " + numerocaracteres + " caracteres.....!!!");
        }
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtPathernKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPathernKeyTyped
        // TODO add your handling code here:
        int k = (int) evt.getKeyChar();
        if (k > 47 && k < 58) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(rootPane, "Solo puede ingresar letras.....!!!");
        }
        int numerocaracteres = 15;
        if (txtPathern.getText().length() >= numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo puede ingresar " + numerocaracteres + " caracteres.....!!!");
        }
    }//GEN-LAST:event_txtPathernKeyTyped

    private void txtMotherKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMotherKeyTyped
        // TODO add your handling code here:
        int k = (int) evt.getKeyChar();
        if (k > 47 && k < 58) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(rootPane, "Solo puede ingresar letras.....!!!");
        }
        int numerocaracteres = 15;
        if (txtMother.getText().length() >= numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo puede ingresar " + numerocaracteres + " caracteres.....!!!");
        }
    }//GEN-LAST:event_txtMotherKeyTyped

    private void txtAccountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccountKeyTyped
        // TODO add your handling code here:
        int numerocaracteres = 15;
        if (txtAccount.getText().length() >= numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo puede ingresar " + numerocaracteres + " caracteres.....!!!");
        }
    }//GEN-LAST:event_txtAccountKeyTyped

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped
        // TODO add your handling code here:
        int numerocaracteres = 15;
        if (txtPass.getText().length() >= numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo puede ingresar " + numerocaracteres + " caracteres.....!!!");
        }
    }//GEN-LAST:event_txtPassKeyTyped

    private void txtRepitPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRepitPassKeyTyped
        // TODO add your handling code here:
        int numerocaracteres = 15;
        if (txtRepitPass.getText().length() >= numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo puede ingresar " + numerocaracteres + " caracteres.....!!!");
        }
    }//GEN-LAST:event_txtRepitPassKeyTyped

    class FondPanel extends JPanel {

        private Image image;

        @Override
        public void paint(Graphics g) {
            image = new ImageIcon(getClass().getResource("/Image/Fondo 2.jpg")).getImage();
            g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    public javax.swing.JComboBox jCnivel;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbAccountError;
    public javax.swing.JLabel lbCheck1;
    public javax.swing.JLabel lbCheck2;
    public javax.swing.JLabel lbCheck3;
    public javax.swing.JLabel lbCheck4;
    public javax.swing.JLabel lbCheck5;
    public javax.swing.JLabel lbCheck6;
    public javax.swing.JLabel lbMotherError;
    public javax.swing.JLabel lbNameError;
    public javax.swing.JLabel lbPassError;
    public javax.swing.JLabel lbPathernError;
    public javax.swing.JLabel lbRepitError;
    public javax.swing.JTextField txtAccount;
    public javax.swing.JTextField txtMother;
    public javax.swing.JTextField txtName;
    public javax.swing.JPasswordField txtPass;
    public javax.swing.JTextField txtPathern;
    public javax.swing.JPasswordField txtRepitPass;
    // End of variables declaration//GEN-END:variables
}
